package edu.ucr.rp.programacion2.proyecto.gui.model;

public enum PaneName {
    BASE, MENU_BAR, ADD_INVENTORY, DELETE_INVENTORY, ADD_CATALOG, DELETE_CATALOG, ADD_ITEM, CATALOG_CONFIG,
    INVENTORY_TABLE,  SHOW_INVENTORY, CREDITS_UI, ABOUT_UI, CREATE_ITEM;
}
